# Generated by Django 4.1.7 on 2023-02-16 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="network",
            name="city_network",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="network",
            name="company_network",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="network",
            name="country_network",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="network",
            name="gbfs_href_network",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="network",
            name="href_network",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="network",
            name="id_network",
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name="network",
            name="latitude_network",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="network",
            name="longitude_network",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="network",
            name="name_network",
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
