# Generated by Django 4.1.7 on 2023-02-16 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0002_network_city_network_network_company_network_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Station",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("id_station", models.CharField(max_length=100)),
                ("uid_station", models.CharField(max_length=60)),
                ("name_station", models.CharField(max_length=60)),
                ("adress_station", models.CharField(max_length=60)),
                ("payment_station", models.CharField(max_length=60)),
                ("payment_terminal_station", models.BooleanField()),
                ("empty_slots_station", models.IntegerField()),
                ("slots_station", models.IntegerField()),
                ("renting_station", models.IntegerField()),
                ("returning_station", models.IntegerField()),
                ("normal_bikes_station", models.IntegerField()),
                ("free_bikes_station", models.IntegerField()),
                ("ebikes_station", models.IntegerField()),
                ("has_ebikes_station", models.BooleanField()),
                ("altitude_station", models.IntegerField()),
                ("latitude_station", models.IntegerField()),
                ("longitude_station", models.IntegerField()),
                ("timestamp_station", models.DateTimeField()),
                ("last_updated_station", models.IntegerField()),
                (
                    "network_station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="App.network"
                    ),
                ),
            ],
        ),
    ]
