# Generated by Django 4.1.7 on 2023-02-17 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0003_station"),
    ]

    operations = [
        migrations.CreateModel(
            name="TableSEA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero", models.CharField(max_length=5)),
                ("nombre", models.CharField(max_length=100)),
                ("tipo", models.CharField(max_length=5)),
                ("region", models.CharField(max_length=15)),
                ("tipologia", models.CharField(max_length=5)),
                ("titular", models.CharField(max_length=100)),
                ("inversion", models.CharField(max_length=10)),
                ("fecha_presentacion", models.CharField(max_length=12)),
                ("estado", models.CharField(max_length=30)),
            ],
        ),
    ]
