# Generated by Django 4.1.7 on 2023-02-17 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0005_alter_station_uid_station"),
    ]

    operations = [
        migrations.AlterField(
            model_name="network",
            name="company_network",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="network",
            name="country_network",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="network",
            name="id_network",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="network",
            name="name_network",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="station",
            name="adress_station",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="station",
            name="name_station",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="station",
            name="payment_station",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="station",
            name="uid_station",
            field=models.CharField(max_length=10),
        ),
    ]
