# Generated by Django 4.1.7 on 2023-02-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0008_alter_tablesea_estado_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tablesea",
            name="estado",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="tablesea",
            name="fecha_presentacion",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="tablesea",
            name="nombre",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="tablesea",
            name="numero",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="tablesea",
            name="region",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="tablesea",
            name="tipo",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="tablesea",
            name="tipologia",
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name="tablesea",
            name="titular",
            field=models.CharField(max_length=250),
        ),
    ]
